name: Jets
version: 1.0
main: me.Jets.JetsMain
author: David_Septyr, Soringaming, Loonyy, Moon243
description: Have dog fights!

commands:
  jets:
    usage: /<command>
    description: Main command
  JetsHelp:
    usage: /<command>
    description: Help message
